### ISSUE TITLE
edfR download does not work R 3.6.1. MacOS 10.14.6

### ISSUE THREAD

**Issue by theo-hub** [jashubbard/edfR_test#9] opened 2019-10-24 08:33 UTC
Hello,

I am currently trying to install the edfR package for R 3.6.1. I'm using a Macbook Pro (MacOS 10.14.6).
I've already installed Eyelink Developer's Kit (EDF API) and then followed the installation guide:
``` R
install.packages('devtools')
library(devtools)
install_github('jashubbard/edfR')
```

devtools is installed successfully. When I'm trying to install edfR, I receive several warnings, e.g., 
In file included from edf_api.cpp:4:
```
./edf.h:51:10: warning: the current #pragma pack aligment value is modified in the included file [-Wpragma-pack]
#include "edf_data.h"
```

Still, the edfR appears in the library. However the installation must be somehow incomplete since I keep on receiving the following error message when I'm trying to load the package: 

```
Error: package or namespace load failed for ‘edfR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/edfR/libs/edfR.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/edfR/libs/edfR.so, 6): Library not loaded:  @executable_path/../Frameworks/edfapi.framework/Versions/A/edfapi
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/edfR/libs/edfR.so
```

**Comment by bzuck-temple** [comment] 2019-10-28 18:38
Edit: I fixed my previous problem. My university security blocked the install of the Eyelink Developer's kit. However I now have the same problem as Theo-hub. Thanks


Original:
I am having the similar problem. However I can not even get the package to download. Is there more information about dependent packages and system requirements? Thanks


`ld: framework not found edfapi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [edfR.so] Error 1
ERROR: compilation failed for package ‘edfR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/edfR’
Error: Failed to install 'edfR' from GitHub:

**Comment by jgeller112** [comment] 2019-10-30 19:18
Interestingly, you can run edfR from R, but not Rstudio. I am not sure if this will be fixed. I think developer is out of the game? @tmalsburg, do you think you might be able to fix this?

**Comment by tmalsburg** [comment] 2019-10-30 19:52
Sorry, I'm neither using MacOS nor RStudio and therefore can't investigate this problem. But I think I have commit rights for this repo, so I could accept merge requests if someone figures out what the problem is.

**Comment by jgeller112** [comment] 2019-10-30 20:03
Thanks for the quick reply! I have tested this on Windows 10 and it also fails. Are you using Linux? Could you try to see if it fails on there?

**Comment by jgeller112** [comment] 2019-10-30 20:23
This seems to be an issue on newest version of R. I have tried older versions and it seems to work just fine.

**Comment by tmalsburg** [comment] 2019-10-30 20:23
Just reinstalled it on current Ubuntu LTS and there were no errors. Loading the package works as well, and when I try it in RStudio, it works, too.  Hm ...

**Comment by tmalsburg** [comment] 2019-10-30 20:24
My version of R is: `R version 3.6.1 (2019-07-05)`

**Comment by tmalsburg** [comment] 2019-10-30 20:30
@theo-hub, could you please check whether the file `/Library/Frameworks/R.framework/Versions/3.6/Resources/library/edfR/libs/edfR.so` exists?

**Comment by jgeller112** [comment] 2019-10-30 21:02
I get this error on Rstudio when loading the library: 

```
Loading required package: RcppArmadillo
Loading required package: data.table
data.table 1.12.2 using 3 threads (see ?getDTthreads).  Latest news: r-datatable.com
Error: package or namespace load failed for ‘edfR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/edfR/libs/edfR.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/edfR/libs/edfR.so, 6): Library not loaded:  @executable_path/../Frameworks/edfapi.framework/Versions/A/edfapi
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/edfR/libs/edfR.so
  Reason: image not found
```

**Comment by theo-hub** [comment] 2019-10-31 07:37
Hi everybody,
yesterday, I finally managed to solve the problem. I could load the package with an older version of RStudio (1.2.1335). Apparently, RStudio was pointing to a wrong version of R. Others are reporting similar issues. So, it might help to have a look at this: https://github.com/rstudio/rstudio/issues/5442

**Comment by jgeller112** [comment] 2019-10-31 14:09
I’m glad this was resolved!

**Comment by jashubbard** [comment] 2019-10-31 17:20
@theo-hub glad that you were able to fix this! BTW, I would love to devote more time to this package but have been pretty busy lately. Hoping I can circle back around to it again soon. I'm considering building a Docker image as an alternative install option, so all the dependencies are in there-- managing the Eyelink libraries is half the battle.

**Closed as completed** 2019-10-31 17:21 UTC
